### ISSUE TITLE
Invite message component

### ISSUE THREAD

**Issue by rahatarmanahmed** [squelch-irc/squelch#13]

**Comment by rahatarmanahmed** [comment]
https://docs.google.com/spreadsheets/d/1lZLP1mzIfSLuoFh9eiT-X1piSmgLJTtVVsZ9DxynWZ8/edit#gid=0

**Comment by seiyria** [comment]
We should also add a button to this to join the channel.

**Comment by rahatarmanahmed** [comment]
Finished in 84ef508

(The button idea is cool but can't do anything about that until we add commands in phase 2 so just remember that one)
