### ISSUE TITLE
Connection indicators

### ISSUE THREAD

**Issue by rahatarmanahmed** [squelch-irc/squelch#19]
Have some kind of indication if the server in the server list is online. Probably easiest to just gray out the text.

**Comment by seiyria** [comment]
Or use an icon, or put it in parenthesis (that's what hexchat does).

**Comment by rahatarmanahmed** [comment]
Icons mean bower dependencies, I don't wanna deal with that until we get to the ming or user config settings

**Comment by seiyria** [comment]
So, parens/italics for now. Icons later.

**Comment by rahatarmanahmed** [comment]
Disconnected servers/ channels you have left now show as grey.
